## 1.Write a program to take a name and age from the user and print a greeting message.

In [1]:
def greet(name,age):

    print(f"Hello {name} and you are {age} years old")

namee = input("Enter Your Name")

agee = int(input("Enter Your Age:"))

greet(namee,agee)

Enter Your Name Sujin
Enter Your Age: 25

Hello Sujin and you are 25 years old

## 2.Create a list of numbers and print only even numbers using a for loop.

In [8]:
numbers = range(1,51)

even_numbers=[]

for i in numbers:
    if i % 2==0:
        even_numbers.append(i)
print(even_numbers)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]

In [3]:
numbers = range(1, 51)

result = list(filter(lambda x: x % 2 == 0, numbers))

print(result)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]

### 3. Write a program that handles division by zero using try-except.

In [16]:
a = int(input("Enter a first Number"))
b= int(input("Enter a Second Number:"))
try:
    result = a/b
    print(result)

except ZeroDivisionError:
    print("Can't Divide by Zero.Please give a Non Zero Number")
finally:
    print("The program ended!!")

Enter a first Number 10
Enter a Second Number: 0

Can't Divide by Zero.Please give a Non Zero Number
The program ended!!

### 4. Given a string, count how many vowels it has.

In [19]:
string = "Hi Sujin!! How are You"

vowels=["a","e","i","o","u","A","E","I","O","U"]

count=0

for i in string:
    if i in vowels:

        count+=1

print(count)

8

### 5. Reverse a list without using built-in functions.

In [20]:
reversing = [1,2,3,4,5,6,7,8,9,10]

print(reversing[::-1])

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

### 6. Create a dictionary with at least 5 key-value pairs and print them.

In [4]:
key_value = {"Name":["Sujin","Divo","Ani","Rani","Jerald"],
            "Age":[25,22,27,48,58],
             "Maths":[90,98,97,99,100],
             "Science":[98,99,100,97,95],
             "Social":[99,86,78,99,99]}
type(key_value)

dict

In [25]:
print(key_value.keys())

dict_keys(['Name', 'Age', 'Maths', 'Science', 'Social'])

In [26]:
print(key_value.values())

dict_values([['Sujin', 'Divo', 'Ani', 'Rani', 'Jerald'], [25, 22, 27, 48, 58], [90, 98, 97, 99, 100], [98, 99, 100, 97, 95], [99, 86, 78, 99, 99]])

In [27]:
print(key_value.items())

dict_items([('Name', ['Sujin', 'Divo', 'Ani', 'Rani', 'Jerald']), ('Age', [25, 22, 27, 48, 58]), ('Maths', [90, 98, 97, 99, 100]), ('Science', [98, 99, 100, 97, 95]), ('Social', [99, 86, 78, 99, 99])])

### Create a Dataframe using htis dictionary

In [5]:
import pandas as pd

df = pd.DataFrame(key_value)
df

     Name  Age  Maths  Science  Social
0   Sujin   25     90       98      99
1    Divo   22     98       99      86
2     Ani   27     97      100      78
3    Rani   48     99       97      99
4  Jerald   58    100       95      99

### Filter rows in a DataFrame where the Age column is greater than 30.

In [7]:
df[df["Age"] > 30]

     Name  Age  Maths  Science  Social
3    Rani   48     99       97      99
4  Jerald   58    100       95      99

In [ ]:
x