### Tope 8 Powerful functions in Python for Deeper Data Analysis

### 1.groupby

In [2]:
import pandas as pd

insurance = pd.read_csv("Insurance.csv")
insurance

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [3]:
insurance.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [8]:
insurance.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

### Pull Up the average values based on region

In [14]:
insurance.groupby("region")["charges"].mean().round(2).sort_values()

region
southwest    12346.94
northwest    12417.58
northeast    13406.38
southeast    14735.41
Name: charges, dtype: float64

### Pull Up the Average values based on Region and Sex

In [16]:
insurance.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [17]:
insurance.groupby(["region","sex"])["charges"].mean().round(2).sort_values()

region     sex
southwest  female    11274.41
northwest  male      12354.12
           female    12479.87
northeast  female    12953.20
southwest  male      13412.88
southeast  female    13499.67
northeast  male      13854.01
southeast  male      15879.62
Name: charges, dtype: float64

### 2.Pivot Table

In [30]:
pd.pivot_table(data=insurance,values="charges",index="region",columns=["sex","children"]).round(2)

sex          female                                                    \
children          0         1         2         3         4         5
region
northeast   9789.82  17124.69  14523.22  13730.10  14542.42       NaN
northwest  12583.87  11118.86  13127.59  13430.71  11024.42   8965.80
southeast  14862.01   9869.91  11766.31  19722.98  18267.10   9923.89
southwest  10149.75  10841.64  16230.26   8438.74  10945.68  10023.65

sex            male
children          0         1         2         3         4         5
region
northeast  13389.64  15474.29  12317.91  14935.22  14442.28   6978.97
northwest   9812.97   9515.04  13762.55  22971.22  11508.32       NaN
southeast  13791.81  17424.65  18647.95  17101.82   8726.91  10306.99
southwest  13727.26   9971.33  18875.95  12071.59  17923.95   6864.67

### 3.Aggregate

Pull Up the Sum,Min.max.mean values based on Region and Sex

In [35]:
insurance.groupby("region")["charges"].agg(["min","max","mean","sum"]).round(2)

               min       max      mean         sum
region
northeast  1694.80  58571.07  13406.38  4343668.58
northwest  1621.34  60021.40  12417.58  4035712.00
southeast  1121.87  63770.43  14735.41  5363689.76
southwest  1241.56  52590.83  12346.94  4012754.65

### 4.Crosstab

How many smokers and non smokers in a region

In [38]:
pd.crosstab(index=insurance["region"],columns=insurance["smoker"],margins=True)

smoker       no  yes   All
region
northeast   257   67   324
northwest   267   58   325
southeast   273   91   364
southwest   267   58   325
All        1064  274  1338

### 6.CONCAT

In [40]:
sales_2017 = pd.read_csv("Sales_Transactions_2017.csv")
sales_2018 = pd.read_csv("Sales_Transactions_2018.csv")
sales_2019 = pd.read_csv("Sales_Transactions_2019.csv")

In [42]:
sales_concat = pd.concat([sales_2017,sales_2018,sales_2019])

In [43]:
sales_concat

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

### 7.Apply

Create a New Column as "Eligibility" and mark as Eligible if age > 20 else Not Eligible

In [44]:
def get_age(age):
    if age > 20:
        return "Eligible"
    else:
        return "Not Eligible"

In [47]:
insurance["Eligibility"] = insurance["age"].apply(get_age)

In [48]:
insurance

,age,sex,bmi,children,smoker,region,charges,Eligibility
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligible
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligible
2,28,male,33.000,3,no,southeast,4449.46200,Eligible
3,33,male,22.705,0,no,northwest,21984.47061,Eligible
4,32,male,28.880,0,no,northwest,3866.85520,Eligible
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligible
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligible
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible

### 8.Lambda

In [52]:
insurance["eligibility_2"] = insurance["age"].apply(lambda x:1 if x>20 else 0)

In [53]:
insurance

,age,sex,bmi,children,smoker,region,charges,Eligibility,eligibility,eligibility_2
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligible,0,0
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligible,0,0
2,28,male,33.000,3,no,southeast,4449.46200,Eligible,1,1
3,33,male,22.705,0,no,northwest,21984.47061,Eligible,1,1
4,32,male,28.880,0,no,northwest,3866.85520,Eligible,1,1
...,...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible,1,1
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligible,0,0
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligible,0,0
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible,1,1
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible,1,1

### del Keyword

In [54]:
del insurance["eligibility"]

In [56]:
insurance

,age,sex,bmi,children,smoker,region,charges,Eligibility,eligibility_2
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligible,0
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligible,0
2,28,male,33.000,3,no,southeast,4449.46200,Eligible,1
3,33,male,22.705,0,no,northwest,21984.47061,Eligible,1
4,32,male,28.880,0,no,northwest,3866.85520,Eligible,1
...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible,1
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligible,0
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligible,0
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible,1
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible,1

In [57]:
del insurance["Eligibility"]

In [58]:
del insurance["eligibility_2"]

In [59]:
insurance

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [60]:
insurance.charges

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [63]:
insurance[["charges","sex"]]

          charges     sex
0     16884.92400  female
1      1725.55230    male
2      4449.46200    male
3     21984.47061    male
4      3866.85520    male
...           ...     ...
1333  10600.54830    male
1334   2205.98080  female
1335   1629.83350  female
1336   2007.94500  female
1337  29141.36030  female

[1338 rows x 2 columns]