## 1.Write a program to take a name and age from the user and print a greeting message.

In [1]:
def greet(name,age):

    print(f"Hello {name} and you are {age} years old")

namee = input("Enter Your Name")

agee = int(input("Enter Your Age:"))

greet(namee,agee)

Enter Your Name Sujin
Enter Your Age: 25

Hello Sujin and you are 25 years old

## 2.Create a list of numbers and print only even numbers using a for loop.

In [1]:
numbers = [1,2,3,4,5,6,7,8,9,10]

even_numbers=[]

for i in numbers:
    if i % 2==0:
        even_numbers.append(i)
print(even_numbers)

[2, 4, 6, 8, 10]

### 3. Write a program that handles division by zero using try-except.

In [2]:
a = int(input("Enter a first Number"))
b= int(input("Enter a Second Number:"))
try:
    result = a/b
    print(result)

except ZeroDivisionError:
    print("Can't Divide by Zero.Please give a Non Zero Number")
finally:
    print("The program ended!!")

Enter a first Number 10
Enter a Second Number: 0

Can't Divide by Zero.Please give a Non Zero Number
The program ended!!

### 4. Given a string, count how many vowels it has.

In [3]:
string = "Hi Sujin!! How are You"

vowels=["a","e","i","o","u","A","E","I","O","U"]

count=0

for i in string:
    if i in vowels:

        count+=1

print(count)

8

### 5. Reverse a list without using built-in functions.

In [4]:
reversing = [1,2,3,4,5,6,7,8,9,10]

print(reversing[::-1])

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

### 6. Create a dictionary with at least 5 key-value pairs and print them.

In [5]:
key_value = {"Name":["Sujin","Divo","Ani","Rani","Jerald"],
            "Age":[25,22,27,48,58],
             "Maths":[90,98,97,99,100],
             "Science":[98,99,100,97,95],
             "Social":[99,86,78,99,99]}
type(key_value)

dict

In [25]:
print(key_value.keys())

dict_keys(['Name', 'Age', 'Maths', 'Science', 'Social'])

In [26]:
print(key_value.values())

dict_values([['Sujin', 'Divo', 'Ani', 'Rani', 'Jerald'], [25, 22, 27, 48, 58], [90, 98, 97, 99, 100], [98, 99, 100, 97, 95], [99, 86, 78, 99, 99]])

In [27]:
print(key_value.items())

dict_items([('Name', ['Sujin', 'Divo', 'Ani', 'Rani', 'Jerald']), ('Age', [25, 22, 27, 48, 58]), ('Maths', [90, 98, 97, 99, 100]), ('Science', [98, 99, 100, 97, 95]), ('Social', [99, 86, 78, 99, 99])])

### 8.Create a Dataframe using this dictionary

In [30]:
import pandas as pd

df = pd.DataFrame(key_value)
df

     Name  Age  Maths  Science  Social
0   Sujin   25     90       98      99
1    Divo   22     98       99      86
2     Ani   27     97      100      78
3    Rani   48     99       97      99
4  Jerald   58    100       95      99

### 10.Filter rows in a DataFrame where the Age column is greater than 30.

In [33]:
df[df["Age"] > 30]

     Name  Age  Maths  Science  Social
3    Rani   48     99       97      99
4  Jerald   58    100       95      99

### 7. Write a Pandas code to read a CSV and print the top 5 rows.

In [10]:
import pandas as pd

employee_data = pd.read_csv("Employee_data.csv")

employee_data.head()

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024

### 9. Replace all missing values in a DataFrame with the column’s mean

I'm going to replace Salary missing value with mean of that column

In [12]:
mean_salary = employee_data["Salary"].mean()

mean_salary

np.float64(62500.0)

In [15]:
employee_data["Salary"].fillna(value=62500,inplace=True)

C:\Users\sujin\AppData\Local\Temp\ipykernel_7736\2998119907.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  employee_data["Salary"].fillna(value=62500,inplace=True)

In [16]:
employee_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech  62500.0  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech  62500.0  12-11-2020