## Chapter:1 Getting and Knowing data

In [2]:
import pandas as pd

order_details = pd.read_csv(filepath_or_buffer="Data.tsv.txt",sep="\t")

order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [3]:
order_details.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [4]:
order_details.tail()

,order_id,quantity,item_name,choice_description,item_price
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

## Data Analysis

In [5]:
order_details.shape

(4622, 5)

In [6]:
order_details.size

23110

In [7]:
order_details.isnull().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [14]:
order_details.isna().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [8]:
order_details.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

In [9]:
order_details.describe()

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

In [10]:
order_details.describe(include="all")

           order_id     quantity     item_name choice_description item_price
count   4622.000000  4622.000000          4622               3376       4622
unique          NaN          NaN            50               1043         78
top             NaN          NaN  Chicken Bowl        [Diet Coke]     $8.75
freq            NaN          NaN           726                134        730
mean     927.254868     1.075725           NaN                NaN        NaN
std      528.890796     0.410186           NaN                NaN        NaN
min        1.000000     1.000000           NaN                NaN        NaN
25%      477.250000     1.000000           NaN                NaN        NaN
50%      926.000000     1.000000           NaN                NaN        NaN
75%     1393.000000     1.000000           NaN                NaN        NaN
max     1834.000000    15.000000           NaN                NaN        NaN

## Fiind out the unique items sold  in the restaurant

In [11]:
order_details.nunique()

order_id              1834
quantity                 9
item_name               50
choice_description    1043
item_price              78
dtype: int64

In [12]:
print(order_details['item_name'].unique())

['Chips and Fresh Tomato Salsa' 'Izze' 'Nantucket Nectar'
 'Chips and Tomatillo-Green Chili Salsa' 'Chicken Bowl' 'Side of Chips'
 'Steak Burrito' 'Steak Soft Tacos' 'Chips and Guacamole'
 'Chicken Crispy Tacos' 'Chicken Soft Tacos' 'Chicken Burrito'
 'Canned Soda' 'Barbacoa Burrito' 'Carnitas Burrito' 'Carnitas Bowl'
 'Bottled Water' 'Chips and Tomatillo Green Chili Salsa' 'Barbacoa Bowl'
 'Chips' 'Chicken Salad Bowl' 'Steak Bowl' 'Barbacoa Soft Tacos'
 'Veggie Burrito' 'Veggie Bowl' 'Steak Crispy Tacos'
 'Chips and Tomatillo Red Chili Salsa' 'Barbacoa Crispy Tacos'
 'Veggie Salad Bowl' 'Chips and Roasted Chili-Corn Salsa'
 'Chips and Roasted Chili Corn Salsa' 'Carnitas Soft Tacos'
 'Chicken Salad' 'Canned Soft Drink' 'Steak Salad Bowl'
 '6 Pack Soft Drink' 'Chips and Tomatillo-Red Chili Salsa' 'Bowl'
 'Burrito' 'Crispy Tacos' 'Carnitas Crispy Tacos' 'Steak Salad'
 'Chips and Mild Fresh Tomato Salsa' 'Veggie Soft Tacos'
 'Carnitas Salad Bowl' 'Barbacoa Salad Bowl' 'Salad' 'Veggie Crispy Tacos'
 'Veggie Salad' 'Carnitas Salad']

## Give me the list of top 5 selling items

In [13]:
order_details.groupby('item_name')["quantity"].sum().sort_values()

item_name
Carnitas Salad                             1
Chips and Mild Fresh Tomato Salsa          1
Veggie Crispy Tacos                        1
Crispy Tacos                               2
Salad                                      2
Steak Salad                                4
Bowl                                       4
Burrito                                    6
Carnitas Salad Bowl                        6
Veggie Salad                               6
Veggie Soft Tacos                          8
Carnitas Crispy Tacos                      8
Chicken Salad                              9
Barbacoa Salad Bowl                       10
Barbacoa Crispy Tacos                     12
Chips and Roasted Chili-Corn Salsa        18
Veggie Salad Bowl                         18
Izze                                      20
Chips and Roasted Chili Corn Salsa        23
Barbacoa Soft Tacos                       25
Chips and Tomatillo-Red Chili Salsa       25
Nantucket Nectar                          29
Steak Salad Bowl                          31
Chips and Tomatillo-Green Chili Salsa     33
Steak Crispy Tacos                        36
Carnitas Soft Tacos                       40
Chips and Tomatillo Green Chili Salsa     45
Chicken Crispy Tacos                      50
Chips and Tomatillo Red Chili Salsa       50
6 Pack Soft Drink                         55
Steak Soft Tacos                          56
Carnitas Burrito                          60
Barbacoa Bowl                             66
Carnitas Bowl                             71
Veggie Bowl                               87
Barbacoa Burrito                          91
Veggie Burrito                            97
Side of Chips                            110
Chicken Soft Tacos                       120
Chicken Salad Bowl                       123
Canned Soda                              126
Chips and Fresh Tomato Salsa             130
Bottled Water                            211
Steak Bowl                               221
Chips                                    230
Canned Soft Drink                        351
Steak Burrito                            386
Chips and Guacamole                      506
Chicken Burrito                          591
Chicken Bowl                             761
Name: quantity, dtype: int64

In [14]:
top5_selling = order_details.groupby("item_name")["quantity"].sum().sort_values(ascending=False).head()

top5_selling

item_name
Chicken Bowl           761
Chicken Burrito        591
Chips and Guacamole    506
Steak Burrito          386
Canned Soft Drink      351
Name: quantity, dtype: int64

## Give me the list of least 5 Selling Items

In [15]:
order_details.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [16]:

least5_selling = order_details.groupby("item_name")["quantity"].sum().sort_values().head()
least5_selling

item_name
Carnitas Salad                       1
Chips and Mild Fresh Tomato Salsa    1
Veggie Crispy Tacos                  1
Crispy Tacos                         2
Salad                                2
Name: quantity, dtype: int64

## Data Cleaning

In [19]:
order_details["item_price"]=order_details["item_price"].str.replace("$","").astype(float)

In [20]:
order_details.describe()

          order_id     quantity   item_price
count  4622.000000  4622.000000  4622.000000
mean    927.254868     1.075725     7.464336
std     528.890796     0.410186     4.245557
min       1.000000     1.000000     1.090000
25%     477.250000     1.000000     3.390000
50%     926.000000     1.000000     8.750000
75%    1393.000000     1.000000     9.250000
max    1834.000000    15.000000    44.250000

## Top 5 selling items individual revenue it made

In [22]:
order_details.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

In [25]:
order_details["total_revenue"] = order_details["quantity"] * order_details["item_price"]
order_details["total_revenue"]

0        2.39
1        3.39
2        3.39
3        2.39
4       33.96
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: total_revenue, Length: 4622, dtype: float64

In [27]:
order_details.head()

,order_id,quantity,item_name,choice_description,item_price,total_revenue
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,33.96

In [45]:
top5_selling_revenue = order_details.groupby("item_name")["total_revenue"].sum().sort_values(ascending=False).head()

top5_selling_revenue

item_name
Chicken Bowl           8044.63
Chicken Burrito        6387.06
Steak Burrito          4236.13
Steak Bowl             2479.81
Chips and Guacamole    2475.62
Name: total_revenue, dtype: float64

## Total Revenue of the top5 items sold

In [50]:
total_revenue_top5_items_sold = top5_selling_revenue.sum()

total_revenue_top5_items_sold

np.float64(23623.25)

## Chapter:4 Filtering,Selection and Sorting

In [53]:
import pandas as pd

euro_data =  pd.read_csv("Eure_2012_Stats_Team.csv")

euro_data

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18

In [70]:
## 

filtered_data = euro_data[["Team","Goals","Red Cards","Yellow Cards"]]
filtered_data

                   Team  Goals  Red Cards  Yellow Cards
0               Croatia      4          0             9
1        Czech Republic      4          0             7
2               Denmark      4          0             4
3               England      5          0             5
4                France      3          0             6
5               Germany     10          0             4
6                Greece      5          1             9
7                 Italy      6          0            16
8           Netherlands      2          0             5
9                Poland      2          1             7
10             Portugal      6          0            12
11  Republic of Ireland      1          1             6
12               Russia      5          0             6
13                Spain     12          0            11
14               Sweden      5          0             7
15              Ukraine      2          0             5

## Top 5 Yellow Cards

In [62]:
filtered_data.sort_values(by="Yellow Cards",ascending=False).head()

        Team  Goals  Red Cards  Yellow Cards
7      Italy      6          0            16
10  Portugal      6          0            12
13     Spain     12          0            11
0    Croatia      4          0             9
6     Greece      5          1             9

## Top 5 red cards

In [66]:
filtered_data.sort_values(by="Red Cards",ascending=False).head()

                   Team  Goals  Red Cards  Yellow Cards
6                Greece      5          1             9
9                Poland      2          1             7
11  Republic of Ireland      1          1             6
0               Croatia      4          0             9
3               England      5          0             5

In [69]:
filtered_data[filtered_data["Red Cards"]  == 1]

                   Team  Goals  Red Cards  Yellow Cards
6                Greece      5          1             9
9                Poland      2          1             7
11  Republic of Ireland      1          1             6

## List the Teams which has got more than 8 yellow cards

In [72]:
filtered_data[filtered_data["Yellow Cards"] > 8]

        Team  Goals  Red Cards  Yellow Cards
0    Croatia      4          0             9
6     Greece      5          1             9
7      Italy      6          0            16
10  Portugal      6          0            12
13     Spain     12          0            11

## Cleaning Data

In [2]:
import pandas as pd

In [3]:
employee_data = pd.read_csv("Employee_data.csv")
employee_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech      NaN  12-11-2020

In [4]:
employee_data.shape

(8, 5)

### First check with Client about the missing values. If they give the missing data, that's good. Else we need to find the ways with handling the data

In [76]:
employee_data.isna().sum()

Name          1
Age           1
Department    0
Salary        2
Join_Date     0
dtype: int64

In [77]:
employee_data.isnull().sum()

Name          1
Age           1
Department    0
Salary        2
Join_Date     0
dtype: int64

In [81]:
employee_data.drop_duplicates(inplace=True)

In [82]:
employee_data.isnull().sum()

Name          1
Age           1
Department    0
Salary        1
Join_Date     0
dtype: int64

In [83]:
employee_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022

In [85]:
employee_data.dropna(inplace=True)

In [86]:
employee_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023

In [87]:
employee_data.shape

(4, 5)

### Step 3:Record it that the client gave total 7 records..we removed 1 duplicate row and 2 NaN rows.

Then send it to Client for the approval. Once the approval is done, move to the next ssteps.